FROM node:22.7-alpine
RUN apk add --no-cache libc6-compat
RUN apk update
ENV NODE_ENV=development
WORKDIR /webview
COPY ./app/webview/package.json .
RUN npm install
COPY ./app/webview .
CMD ["npm", "run", "dev"]